### ISSUE TITLE
InvalidPathException: Found empty property at index

### ISSUE THREAD

**Issue by ATRG** [IBM/transformation-advisor-sdk#101]
**Describe the bug**
Get an InvalidPathException error when trying to parse an issue where the matched issue has a comma in the name.

**To Reproduce**
1. Have an assessment that results in a data.json containing something like:
```
{ "Name, with a comma" : { "This Object": "Triggers an Issue" } }
```
2. Run the assessment that results in the data.json above
3. get the following error, without any recommendations.json being created:
```Exception in thread "main" com.jayway.jsonpath.InvalidPathException: Found empty property at index 93
        at com.jayway.jsonpath.internal.path.PathCompiler.fail(PathCompiler.java:616)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:579)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124)
        at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58)
        at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75)
        at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
        at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:87)
        at com.ibm.ta.sdk.core.detector.json.JsonIssueRuleTypeProvider.getOccurrence(JsonIssueRuleTypeProvider.java:150)
        at com.ibm.ta.sdk.core.detector.json.JsonIssueRuleTypeProvider.getIssue(JsonIssueRuleTypeProvider.java:112)
        at com.ibm.ta.sdk.core.assessment.IssueRuleProcessor.processIssues(IssueRuleProcessor.java:106)
        at com.ibm.ta.sdk.core.assessment.GenericRecommendation.getIssues(GenericRecommendation.java:107)
        at com.ibm.ta.sdk.spi.assess.RecommendationJson.<init>(RecommendationJson.java:86)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runAssess(TADataCollector.java:309)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runRun(TADataCollector.java:375)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runCommand(TADataCollector.java:134)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.main(TADataCollector.java:668)```

**Expected behavior**
No error and a recommendations.json that finds the issue under the object which has a comma in its name.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java version: IBM JDK 1.8
 - TA-SDK Version: 0.6.3

**Additional context**
Add any other context about the problem here.

**Comment by transformationAdvisor-sdk** [comment]
This problem looks like is the same issue of this one(https://github.com/json-path/JsonPath/issues/400),  which is already being fixed in the json-path package. 
Will update the json-path package version to 2.7.0 to resolve this problem.

**Comment by transformationAdvisor-sdk** [comment]
fixed
