### ISSUE TITLE
Collection validation failed when upload to TA server

### ISSUE THREAD

**Issue by transformationAdvisor-sdk** [IBM/transformation-advisor-sdk#106]
When upload the latest IIB collection to TA server, it failed.

Here is the error message find from TA server
```
[11/2/22, 10:01:19:732 EDT] 00000030 SystemErr                                                    R 
10:01:19.730: com.ibm.cloud.lands.landsserver.SdkApi: 
ERROR: validation failed: : com.ibm.ta.sdk.spi.plugin.TAException: Invalid collection archive.
Anomaly found. Number of asessment unit directories in archive does not match data in environment JSON.
	at com.ibm.ta.sdk.spi.validation.TaCollectionZipValidator.validateArchive(TaCollectionZipValidator.java:160)
	at com.ibm.ta.sdk.spi.validation.TaCollectionZipValidator.validateCollectionArchive(TaCollectionZipValidator.java:48)
	at com.ibm.cloud.lands.landsserver.SdkApi.validateSdkZipFile(SdkApi.java:118)
	at com.ibm.cloud.lands.landsserver.SdkApi.submitData(SdkApi.java:63)
	at com.ibm.cloud.lands.landsserver.CollectionApi.submitDataCollectorOutput(CollectionApi.java:315)
	at com.ibm.cloud.lands.landsserver.CollectionApi.submitDataCollectorOutput(CollectionApi.java:213)
	at com.ibm.cloud.lands.landsserver.API.Resources.CollectionArchive.create(CollectionArchive.java:177)
	at com.ibm.cloud.lands.landsserver.API.API_V2.createCollectionResult(API_V2.java:2324)
```

**Environment (please complete the following information):**
 - OS: All
 - Java version: All
 - TA-SDK Version 0.6.5

**Additional context**

**Comment by transformationAdvisor-sdk** [comment]
done
