### ISSUE TITLE
Unicode single quotes cause a jsonpath.InvalidPathException

### ISSUE THREAD

**Issue by ATRG** [IBM/transformation-advisor-sdk#114]
**Describe the bug**
Strings containing unicode single quotes that are passed in to jsonpath result in a jsonpath.InvalidPathException
```
Exception in thread "main" com.jayway.jsonpath.InvalidPathException: Property must be separated by comma or Property must be terminated close square bracket at index 159
        at com.jayway.jsonpath.internal.path.PathCompiler.fail(PathCompiler.java:616)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:586)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
        at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
        at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124)
        at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58)
        at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75)
        at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
        at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:87)
        at com.ibm.ta.sdk.core.detector.json.JsonIssueRuleTypeProvider.getOccurrence(JsonIssueRuleTypeProvider.java:150)
        at com.ibm.ta.sdk.core.detector.json.JsonIssueRuleTypeProvider.getIssue(JsonIssueRuleTypeProvider.java:112)
        at com.ibm.ta.sdk.core.assessment.IssueRuleProcessor.processIssues(IssueRuleProcessor.java:106)
        at com.ibm.ta.sdk.core.assessment.GenericRecommendation.getIssues(GenericRecommendation.java:107)
        at com.ibm.ta.sdk.spi.assess.RecommendationJson.<init>(RecommendationJson.java:86)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runAssess(TADataCollector.java:315)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runRun(TADataCollector.java:381)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runCommand(TADataCollector.java:140)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.main(TADataCollector.java:674)
```

**To Reproduce**
1. Have a recommendation path that has a member with a single quote in it, such as `Problem + \u0027String\u0027`.
2. Run the TA-SDK against it, and watch the exception occur when it encounters the single quote.

**Expected behavior**
No exception to occur, and TA to continue to analyse the problem.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Linux-RedHat]
 - Java version: [e.g. IBM JDK 1.8, OpenJDK 1.9]
 - TA-SDK Version 0.6.9

**Additional context**
I think we may be able to avoid this by pre-parsing any strings that are about to be passed to jsonpath and padding any encountered `\` with another backslash, i.e. turning the problem string `Problem + \u0027String\u0027` in to `Problem + \\u0027String\\u0027`.

**Comment by transformationAdvisor-sdk** [comment]
single quote is a a special character reserved in json path.
For this issue,  we will replace single quote with double quote before process the json file.
