### ISSUE TITLE
Using Arrays.asList() to construct cli option cause command failure

### ISSUE THREAD

**Issue by transformationAdvisor-sdk** [IBM/transformation-advisor-sdk#84]
**Describe the bug**
Problem is reported by the IIB team when upgrade their plugin to SDK 0.6.0
java -jar target\ta-plugin-ace.jar ace collect
Exception in thread "main" java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:159)
        at java.util.AbstractList.add(AbstractList.java:119)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runCommand(TADataCollector.java:75)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.main(TADataCollector.java:668)

**To Reproduce**
1. In the plugin provider java file,  override the getAssessCommand() method.
2. In that method construct the cli option like this:
`private static final List<CliInputOption> cmdOpts = Arrays.asList(
            new CliInputOption("s", "server", "Extract a specific server. For use with backups only.", 
                    true, true, "SERVER_NAME", ""));`
3. build the plugin and invoke the assess command

**Expected behavior**
The assess command should complete successfully.

**Screenshots**

**Environment (please complete the following information):**
 - OS: all
 - Java version: 1.8
 - TA-SDK Version: 0.6.0

**Additional context**
N/A

**Comment by transformationAdvisor-sdk** [comment]
We try to insert the target to the command option.
But Arrays.asList() create the fixed List object,  it cannot ass or remove from that list.

Need to update the code to create a new option list,  and add all the command options to that new list,  then add the target option.

**Comment by transformationAdvisor-sdk** [comment]
fixed in version 0.6.1
