### ISSUE TITLE
get NPE when there is no template files existing under the template dir

### ISSUE THREAD

**Issue by transformationAdvisor-sdk** [IBM/transformation-advisor-sdk#99]
**Describe the bug**
get NPE when there is no template files existing under the template dir

**To Reproduce**
1. in the plugin project
2. leave the resources template dir empty.
3. build the plugin project, invoke the run command 

**Expected behavior**
run command should complete successfully.

**Screenshots**

**Environment (please complete the following information):**
 - OS: All
 - Java version: All
 - TA-SDK Version [e.g. 0.6.1]

**Additional context**
```
Exception in thread "main" java.lang.NullPointerException
        at com.ibm.ta.sdk.spi.util.Util.copyResourceToDir(Util.java:149)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.collectData(TADataCollector.java:188)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runAssess(TADataCollector.java:293)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runRun(TADataCollector.java:386)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.runCommand(TADataCollector.java:145)
        at com.ibm.ta.sdk.spi.plugin.TADataCollector.main(TADataCollector.java:679)
```

**Comment by transformationAdvisor-sdk** [comment]
fixed
